/**
 * @file protimer.h
 * @brief Productivity Timer State Machine Header
 * 
 * This file contains the type definitions, data structures, and function prototypes
 * for the Productivity Timer Finite State Machine (FSM). The timer helps users track
 * work productivity sessions with configurable countdown, pause/resume functionality,
 * and statistics tracking.
 * 
 * @note This project is originally a proposed exercise from the FastBit Embedded Brain Academy
 *       UML State Machine Design course.
 * 
 * @author Santiago Rincón Carreño
 * @date October 28, 2025
 */

#ifndef __PROTIMER_INC_
#define __PROTIMER_INC_

#include <stdint.h>

/**
 * @enum protimer_signal_t
 * @brief Event signals for the Productivity Timer FSM
 * 
 * Defines all possible signals that can trigger state transitions or actions
 * within the productivity timer state machine. Signals are divided into external
 * (user-generated) and internal (FSM-generated) categories.
 */
typedef enum protimer_signal_ {
    /* External activity signals - Generated by user interactions */
    PROTIMER_SIGNAL_INC_TIME = 0x00,  /**< Increment time signal - User pressed the '+' button */
    PROTIMER_SIGNAL_DEC_TIME,          /**< Decrement time signal - User pressed the '-' button */
    PROTIMER_SIGNAL_TIME_TICK,         /**< General system tick signal - Periodic time tick event */
    PROTIMER_SIGNAL_START_PAUSE,       /**< Start/Pause toggle signal - User pressed the Start/Stop button */
    PROTIMER_SIGNAL_ABORT,             /**< Abort signal - User pressed both '+' and '-' buttons simultaneously */

    /* Internal activity signals - Generated by the FSM */
    PROTIMER_SIGNAL_ENTRY,             /**< Entry signal - Triggered when entering a state */
    PROTIMER_SIGNAL_EXIT,              /**< Exit signal - Triggered when exiting a state */

    PROTIMER_SIGNAL_TOTAL,             /**< Total number of defined signals */

} protimer_signal_t;

/**
 * @enum protimer_event_status_t
 * @brief Event processing status codes
 * 
 * Defines the possible outcomes after an event is processed by a state handler.
 * This allows the FSM dispatcher to determine appropriate follow-up actions.
 */
typedef enum protimer_event_status_ {
    PROTIMER_EVENT_HANDLED = 0x00,  /**< Event was successfully handled by the current state */
    PROTIMER_EVENT_IGNORED,         /**< Event was ignored by the current state (no action taken) */
    PROTIMER_EVENT_TRANSITION,      /**< Event caused a state transition */

} protimer_event_status_t;

/**
 * @struct protimer_event_t
 * @brief Event structure for the Productivity Timer FSM
 * 
 * Encapsulates an event that will be dispatched to the state machine.
 * Contains the signal type that identifies the event.
 */
typedef struct protimer_event_ {
    protimer_signal_t signal;  /**< The signal type of this event */

} protimer_event_t;

/**
 * @enum protimer_state_t
 * @brief State identifiers for the Productivity Timer FSM
 * 
 * Defines all possible states in the productivity timer state machine.
 * The FSM transitions between these states based on user input and internal events.
 */
typedef enum protimer_state_ {
    PROTIMER_STATE_IDLE = 0x00,  /**< IDLE state - No time set, waiting for user input */
    PROTIMER_STATE_TIME_SET,     /**< TIME_SET state - User is configuring the work duration */
    PROTIMER_STATE_COUNTDOWN,    /**< COUNTDOWN state - Active countdown in progress */
    PROTIMER_STATE_PAUSE,        /**< PAUSE state - Countdown is paused */
    PROTIMER_STATE_STATS,        /**< STATS state - Displaying work statistics */

    PROTIMER_STATE_ID_TOTAL,     /**< Total number of defined states */

} protimer_state_t;

/**
 * @struct protimer_t
 * @brief Main Productivity Timer state machine object
 * 
 * This structure holds all the state and data for a productivity timer instance.
 * It maintains the current state, time values, and a general-purpose tick counter.
 */
typedef struct protimer_ {
    protimer_state_t active_state;  /**< Currently active state of the FSM */

    uint32_t worked_time;   /**< Total accumulated worked time across all sessions (in seconds) */
    uint32_t current_time;  /**< Current countdown time remaining (in seconds) */
    uint32_t elapsed_time;  /**< Time elapsed in the current work session (in seconds) */

    uint32_t tick;  /**< General-purpose tick counter for timing operations */

} protimer_t;

/**
 * @brief Initialize the Productivity Timer state machine
 * 
 * Sets all fields to default values and initializes the FSM to IDLE state.
 * Must be called before using the timer.
 * 
 * @param[in,out] mobj Pointer to the protimer object to initialize
 */
void protimer_init(protimer_t *const mobj);

/**
 * @brief Dispatch an event to the state machine
 * 
 * Processes an event according to the current state's behavior.
 * May result in state transitions and/or data updates.
 * 
 * @param[in,out] mobj Pointer to the protimer object
 * @param[in] event Pointer to the event to process
 */
void protimer_dispatch(protimer_t *const mobj, const protimer_event_t *const event);

#endif /* __PROTIMER_INC_ */